-- SQL INSERT Statements for LoaiSanPham
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Combo/Sản phẩm hot', N'Các bộ kit, combo sản phẩm hot trong cửa hàng.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Vi điều khiển & KIT phát triển', N'Các loại vi điều khiển và bộ kit phát triển như Arduino, STM32, ESP32.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Tool, thiết bị, phụ kiện', N'Dụng cụ, thiết bị đo lường, phụ kiện hỗ trợ điện tử.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Quản lý nhiệt độ', N'Linh kiện và giải pháp quản lý nhiệt độ như tản nhiệt, quạt, keo tản nhiệt.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Connectors', N'Các loại đầu nối, jack cắm điện và tín hiệu.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Cơ điện tử', N'Linh kiện kết hợp điện và cơ khí như động cơ, solenoid, actuator.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Nguồn', N'Các thiết bị cung cấp và chuyển đổi nguồn điện.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'PIN', N'Các loại pin và ắc quy dùng cho thiết bị điện tử.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Linh kiện thụ động', N'Các linh kiện không yêu cầu nguồn ngoài để hoạt động như điện trở, tụ điện, cuộn cảm.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Linh kiện bán dẫn', N'Các linh kiện hoạt động dựa trên tính chất bán dẫn như transistor, diode.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'IC chức năng', N'Các mạch tích hợp chuyên biệt cho một chức năng nhất định.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'LED – Chiếu sáng', N'Các loại đèn LED và module chiếu sáng.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Thu phát không dây', N'Các module và IC hỗ trợ giao tiếp không dây như Bluetooth, Wi-Fi, LoRa.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Cảm biến', N'Các thiết bị phát hiện và đo lường các thông số vật lý.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Module', N'Các module tích hợp sẵn chức năng để dễ dàng phát triển ứng dụng.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Màn hình – LCD', N'Các loại màn hình hiển thị LCD, OLED.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Quang điện tử', N'Các linh kiện chuyển đổi tín hiệu quang sang điện hoặc ngược lại.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Dây điện', N'Các loại dây dẫn điện và cáp tín hiệu.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Tool test', N'Dụng cụ và thiết bị dùng để kiểm tra, debug mạch điện tử.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Hộp nhựa, nhôm', N'Vỏ hộp, vỏ bảo vệ cho các dự án điện tử.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'IoT / Smart Home', N'Các sản phẩm và module cho ứng dụng Internet of Things và nhà thông minh.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Audio & Video', N'Các linh kiện và module liên quan đến xử lý âm thanh và hình ảnh.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Robot, mô hình', N'Linh kiện và bộ phận dùng để lắp ráp robot, mô hình.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Điện tử dân dụng', N'Các linh kiện và sản phẩm điện tử dùng trong gia đình.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Điện tử công nghiệp', N'Các linh kiện và sản phẩm điện tử chuyên dụng trong công nghiệp.');
INSERT INTO LoaiSanPham (TenLoaiSanPham, MoTa) VALUES (N'Sản phẩm ứng dụng / chính hãng', N'Các sản phẩm hoàn chỉnh hoặc linh kiện chính hãng đặc biệt.');

-- SQL INSERT Statements for SanPham
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Điện trở dán 10 Ω 0.125W', 300, '2025-02-10', N'{"Giá trị": "10 Ω", "Công suất/Điện áp": "0.125 W", "Dung sai": "±1%", "Kiểu đóng gói": "SMD 0603"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Điện trở dán 10 kΩ 0.125W', 700, '2023-12-30', N'{"Giá trị": "10 kΩ", "Công suất/Điện áp": "0.125 W", "Dung sai": "±1%", "Kiểu đóng gói": "SMD 0603"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Điện trở xuyên lỗ 100 Ω 0.25W', 500, '2025-01-01', N'{"Giá trị": "100 Ω", "Công suất/Điện áp": "0.25 W", "Dung sai": "±5%", "Kiểu đóng gói": "Axial"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Điện trở xuyên lỗ 1 kΩ 0.25W', 700, '2024-06-25', N'{"Giá trị": "1 kΩ", "Công suất/Điện áp": "0.25 W", "Dung sai": "±5%", "Kiểu đóng gói": "Axial"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Tụ hóa 0.1 µF 16V', 600, '2023-07-03', N'{"Giá trị": "0.1 µF", "Công suất/Điện áp": "16 V", "Dung sai": "±10%", "Kiểu đóng gói": "Radial"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Tụ hóa 10 µF 16V', 1300, '2023-12-21', N'{"Giá trị": "10 µF", "Công suất/Điện áp": "16 V", "Dung sai": "±10%", "Kiểu đóng gói": "Radial"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Tụ gốm 1 µF 50V', 1000, '2025-01-14', N'{"Giá trị": "1 µF", "Công suất/Điện áp": "50 V", "Dung sai": "±5%", "Kiểu đóng gói": "SMD 1206"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cuộn cảm lõi không khí 10 nH', 1200, '2025-04-24', N'{"Giá trị": "10 nH", "Công suất/Điện áp": "1 A", "Dung sai": "±5%", "Kiểu đóng gói": "Through-Hole"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cuộn cảm hình xuyến 100 µH', 3000, '2024-08-18', N'{"Giá trị": "100 µH", "Công suất/Điện áp": "1 A", "Dung sai": "±5%", "Kiểu đóng gói": "Through-Hole"}', 'LSP0009');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Transistor NPN 50V 0.1A TO-92', 1600, '2024-06-09', N'{"Chức năng": "Chuyển mạch, Khuếch đại", "Điện áp Vce/Vrrm": "50 V", "Dòng Ic/If": "0.1 A", "Kiểu đóng gói": "TO-92"}', 'LSP0010');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Transistor PNP 100V 1A SOT-23', 3500, '2024-01-16', N'{"Chức năng": "Chuyển mạch, Khuếch đại", "Điện áp Vce/Vrrm": "100 V", "Dòng Ic/If": "1 A", "Kiểu đóng gói": "SOT-23"}', 'LSP0010');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Diode chỉnh lưu 400V 5A DO-41', 7300, '2025-02-04', N'{"Chức năng": "Chỉnh lưu", "Điện áp Vce/Vrrm": "400 V", "Dòng Ic/If": "5 A", "Kiểu đóng gói": "DO-41"}', 'LSP0010');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'MOSFET 600V 20A TO-220', 21600, '2024-06-06', N'{"Chức năng": "Chuyển mạch công suất", "Điện áp Vce/Vrrm": "600 V", "Dòng Ic/If": "20 A", "Kiểu đóng gói": "TO-220"}', 'LSP0010');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Op-amp LM741 DIP-8 (1 kênh)', 7200, '2024-04-14', N'{"Chức năng": "Khuếch đại thuật toán", "Điện áp hoạt động": "5V", "Kiểu đóng gói": "DIP-8", "Số kênh": "1"}', 'LSP0011');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'IC thời gian NE555 DIP-8 (1 kênh)', 6300, '2024-11-26', N'{"Chức năng": "Tạo xung, Hẹn giờ", "Điện áp hoạt động": "5V", "Kiểu đóng gói": "DIP-8", "Số kênh": "1"}', 'LSP0011');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ điều chỉnh điện áp LM7805 TO-220 (1 kênh)', 8900, '2024-12-06', N'{"Chức năng": "Ổn áp", "Điện áp hoạt động": "12V", "Kiểu đóng gói": "TO-220", "Số kênh": "1"}', 'LSP0011');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Driver động cơ L298N DIP-16 (2 kênh)', 27500, '2023-09-28', N'{"Chức năng": "Điều khiển động cơ", "Điện áp hoạt động": "12V", "Kiểu đóng gói": "DIP-16", "Số kênh": "2"}', 'LSP0011');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ chuyển đổi ADC ADS1115 QFN (4 kênh)', 49500, '2024-08-11', N'{"Chức năng": "Chuyển đổi Analog-Digital", "Điện áp hoạt động": "3.3V", "Kiểu đóng gói": "QFN", "Số kênh": "4"}', 'LSP0011');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'ATmega328P 32KB Flash 2KB RAM 16MHz', 28800, '2025-01-20', N'{"Kiến trúc": "8-bit AVR", "Bộ nhớ Flash (KB)": "32", "RAM (KB)": "2", "Tốc độ xung nhịp (MHz)": "16", "Tính năng": "ADC, PWM, SPI, I2C, UART"}', 'LSP0002');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Raspberry Pi Pico 2MB Flash 264KB RAM 133MHz', 78800, '2023-09-24', N'{"Kiến trúc": "32-bit ARM Cortex-M0+", "Bộ nhớ Flash (KB)": "2000", "RAM (KB)": "264", "Tốc độ xung nhịp (MHz)": "133", "Tính năng": "GPIOs, ADC"}', 'LSP0002');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'STM32F103C8T6 64KB Flash 20KB RAM 72MHz', 64800, '2024-01-19', N'{"Kiến trúc": "32-bit ARM Cortex-M3", "Bộ nhớ Flash (KB)": "64", "RAM (KB)": "20", "Tốc độ xung nhịp (MHz)": "72", "Tính năng": "USB, CAN"}', 'LSP0002');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Arduino Uno R3 (ATmega328P)', 86400, '2024-07-19', N'{"Kiến trúc": "8-bit AVR", "Bộ nhớ Flash (KB)": "32", "RAM (KB)": "2", "Tốc độ xung nhịp (MHz)": "16", "Tính năng": "ADC, PWM, SPI, I2C, UART"}', 'LSP0002');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'ESP32-WROOM-32 4MB Flash 520KB RAM 240MHz', 332800, '2025-06-02', N'{"Kiến trúc": "32-bit Xtensa LX6", "Bộ nhớ Flash (KB)": "4096", "RAM (KB)": "520", "Tốc độ xung nhịp (MHz)": "240", "Tính năng": "WiFi, Bluetooth"}', 'LSP0002');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Băng dính cách điện PVC', 10000, '2023-09-07', N'{"Loại": "Băng dính PVC", "Đặc điểm": "Chịu nhiệt"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây kẽm hàn độ tinh khiết cao', 15000, '2024-03-09', N'{"Loại": "Dây kẽm hàn", "Đặc điểm": "Độ tinh khiết cao"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Kìm cắt linh kiện 6 inch', 27000, '2024-11-19', N'{"Loại": "Kìm cắt chéo", "Đặc điểm": "Kích thước 6 inch"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Hộp đựng linh kiện có ngăn chia', 40000, '2023-09-14', N'{"Loại": "Hộp đựng linh kiện", "Đặc điểm": "Có ngăn chia"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Mỏ hàn nhiệt 60W', 80000, '2024-12-18', N'{"Loại": "Mỏ hàn nhiệt", "Đặc điểm": "Công suất 60W"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Đồng hồ vạn năng tự động đo', 220000, '2024-06-13', N'{"Loại": "Đồng hồ số", "Đặc điểm": "Tự động đo"}', 'LSP0003');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Keo tản nhiệt 5g', 12000, '2025-03-09', N'{"Loại": "Thermal paste", "Kích thước": "5g", "Công suất": "N/A"}', 'LSP0004');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Quạt DC làm mát 12V 25x25x10mm', 24300, '2025-04-02', N'{"Loại": "Active fan", "Kích thước": "25x25x10mm", "Công suất": "12V"}', 'LSP0004');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Tản nhiệt nhôm 40x40x10mm', 40000, '2024-05-25', N'{"Loại": "Passive heatsink", "Kích thước": "40x40x10mm", "Công suất": "N/A"}', 'LSP0004');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module tản nhiệt Peltier 60W', 121000, '2023-07-01', N'{"Loại": "Thermoelectric cooler", "Kích thước": "40x40mm", "Công suất": "60W"}', 'LSP0004');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Header Pin đực 2 chân 2.54mm', 800, '2024-07-01', N'{"Số chân": "2", "Loại": "Thẳng", "Kích thước": "2.54mm", "Ứng dụng": "Kết nối dây"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Jack DC 2.1mm', 1100, '2023-10-08', N'{"Số chân": "2", "Loại": "Male", "Kích thước": "2.1mm", "Ứng dụng": "Cấp nguồn"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Jack Audio 3.5mm Stereo', 2800, '2023-12-30', N'{"Số chân": "3", "Loại": "Male", "Kích thước": "3.5mm", "Ứng dụng": "Truyền dữ liệu"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Header Pin cái 40 chân 2.54mm', 6300, '2024-03-30', N'{"Số chân": "40", "Loại": "Thẳng", "Kích thước": "2.54mm", "Ứng dụng": "Kết nối dây"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cổng USB Type-C Female', 9200, '2023-11-15', N'{"Số chân": "24", "Loại": "Female", "Kích thước": "N/A", "Ứng dụng": "Truyền dữ liệu"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Terminal Block 5 chân', 2100, '2024-06-25', N'{"Số chân": "5", "Loại": "Thẳng", "Kích thước": "N/A", "Ứng dụng": "Kết nối dây"}', 'LSP0005');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Solenoid điện từ 5V Lực kéo 10N', 36100, '2024-01-12', N'{"Điện áp": "5V", "Tốc độ/Mô-men xoắn": "Lực kéo 10N", "Kích thước": "Mini"}', 'LSP0006');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Động cơ DC giảm tốc 3-12V 100 RPM', 45400, '2024-08-20', N'{"Điện áp": "3-12V", "Tốc độ/Mô-men xoắn": "100 RPM", "Kích thước": "Mini"}', 'LSP0006');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Servo TowerPro SG90 5V 2.5 kg.cm', 75800, '2025-01-22', N'{"Điện áp": "5V", "Tốc độ/Mô-men xoắn": "2.5 kg.cm", "Kích thước": "22x12mm"}', 'LSP0006');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Động cơ bước NEMA 17 12V 0.4 Nm', 165000, '2025-01-24', N'{"Điện áp": "12V", "Tốc độ/Mô-men xoắn": "0.4 Nm", "Kích thước": "42x42mm"}', 'LSP0006');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Actuator tuyến tính 24V Hành trình 50mm', 363000, '2025-05-08', N'{"Điện áp": "24V", "Tốc độ/Mô-men xoắn": "Hành trình 50mm", "Kích thước": "N/A"}', 'LSP0006');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module nguồn USB-C 5V 1A', 29200, '2023-11-05', N'{"Điện áp đầu vào": "5VDC", "Điện áp đầu ra": "5VDC", "Dòng điện đầu ra": "1A", "Công suất": "5W"}', 'LSP0007');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ chuyển đổi DC-DC Buck 5V 3A', 68000, '2024-02-28', N'{"Điện áp đầu vào": "4.5-28VDC", "Điện áp đầu ra": "5VDC", "Dòng điện đầu ra": "3A", "Công suất": "15W"}', 'LSP0007');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Adapter AC-DC 12V 2A 24W', 110000, '2025-06-09', N'{"Điện áp đầu vào": "100-240VAC", "Điện áp đầu ra": "12VDC", "Dòng điện đầu ra": "2A", "Công suất": "24W"}', 'LSP0007');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Nguồn DIN Rail 24V 5A 120W', 697000, '2024-04-05', N'{"Điện áp đầu vào": "85-264VAC", "Điện áp đầu ra": "24VDC", "Dòng điện đầu ra": "5A", "Công suất": "120W"}', 'LSP0007');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Pin CR2032 3V 220mAh', 9600, '2023-07-16', N'{"Kích thước": "CR2032", "Điện áp": "3V", "Dung lượng": "220mAh", "Loại": "Không sạc"}', 'LSP0008');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Pin AA Alkaline 1.5V 2700mAh', 19800, '2023-11-26', N'{"Kích thước": "AA", "Điện áp": "1.5V", "Dung lượng": "2700mAh", "Loại": "Không sạc"}', 'LSP0008');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Pin sạc NiMH AAA 1.2V 800mAh', 19400, '2023-10-17', N'{"Kích thước": "AAA", "Điện áp": "1.2V", "Dung lượng": "800mAh", "Loại": "Sạc lại"}', 'LSP0008');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Pin Lithium-ion 18650 3.7V 2200mAh', 60500, '2023-11-02', N'{"Kích thước": "18650", "Điện áp": "3.7V", "Dung lượng": "2200mAh", "Loại": "Sạc lại"}', 'LSP0008');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module sạc pin TP4056', 25000, '2024-04-22', N'{"Kích thước": "N/A", "Điện áp": "N/A", "Dung lượng": "N/A", "Loại": "Module sạc"}', 'LSP0008');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'LED đơn 5mm đỏ 2.0V 2000mcd', 500, '2024-07-21', N'{"Màu sắc": "Đỏ", "Kích thước": "5mm", "Điện áp thuận": "2.0V", "Độ sáng": "2000 mcd"}', 'LSP0012');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'LED SMD 5050 RGB 3.2V 12lm', 5400, '2023-07-11', N'{"Màu sắc": "RGB", "Kích thước": "5050", "Điện áp thuận": "3.2V", "Độ sáng": "12 lm"}', 'LSP0012');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây LED RGB (1m)', 25300, '2024-05-01', N'{"Màu sắc": "RGB", "Kích thước": "N/A", "Điện áp thuận": "12V", "Độ sáng": "N/A"}', 'LSP0012');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module LED ma trận 8x8', 54500, '2024-03-18', N'{"Màu sắc": "Đơn sắc", "Kích thước": "8x8", "Điện áp thuận": "5V", "Độ sáng": "500 cd/m2"}', 'LSP0012');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Anten 2.4GHz', 11000, '2024-04-06', N'{"Chuẩn": "N/A", "Tần số": "2.4GHz", "Giao tiếp": "N/A", "Khoảng cách": "N/A"}', 'LSP0013');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Bluetooth HC-05 (UART 10m)', 35200, '2024-09-11', N'{"Chuẩn": "Bluetooth 2.0", "Tần số": "2.4GHz", "Giao tiếp": "UART", "Khoảng cách": "10m"}', 'LSP0013');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Wi-Fi ESP-01 (UART 400m)', 66000, '2024-01-24', N'{"Chuẩn": "Wi-Fi 802.11b/g/n", "Tần số": "2.4GHz", "Giao tiếp": "UART", "Khoảng cách": "400m"}', 'LSP0013');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Zigbee CC2530 (SPI 1km)', 132000, '2025-03-19', N'{"Chuẩn": "Zigbee", "Tần số": "2.4GHz", "Giao tiếp": "SPI", "Khoảng cách": "1km"}', 'LSP0013');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module LoRa SX1278 (SPI 1km)', 162000, '2024-09-19', N'{"Chuẩn": "LoRaWAN", "Tần số": "433/868/915MHz", "Giao tiếp": "SPI", "Khoảng cách": "1km"}', 'LSP0013');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Quang trở LDR GL5528 (Analog)', 6500, '2024-04-09', N'{"Thông số đo": "Cường độ ánh sáng", "Dải đo": "Analog", "Đầu ra": "Analog"}', 'LSP0014');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến nhiệt độ LM35 (Analog)', 10800, '2024-08-22', N'{"Thông số đo": "Nhiệt độ", "Dải đo": "-55 đến 150°C", "Đầu ra": "Analog"}', 'LSP0014');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến độ ẩm DHT11 (Digital)', 18000, '2023-12-04', N'{"Thông số đo": "Nhiệt độ, Độ ẩm", "Dải đo": "0 đến 50°C", "Đầu ra": "Digital"}', 'LSP0014');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến siêu âm HC-SR04 (Digital)', 25000, '2024-06-25', N'{"Thông số đo": "Khoảng cách", "Dải đo": "3cm - 450cm", "Đầu ra": "Digital"}', 'LSP0014');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến gia tốc MPU6050 (I2C)', 60500, '2024-11-07', N'{"Thông số đo": "Gia tốc, Con quay hồi chuyển", "Dải đo": "±16g", "Đầu ra": "I2C"}', 'LSP0014');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Cảm ứng chạm TTP223 (1 kênh)', 13500, '2024-12-11', N'{"Chức năng": "Phát hiện chạm", "Điện áp": "5V", "Số kênh": "1"}', 'LSP0015');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Cảm biến mưa (1 kênh)', 16200, '2024-06-29', N'{"Chức năng": "Phát hiện mưa", "Điện áp": "5V", "Số kênh": "1"}', 'LSP0015');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Relay 5V 1 kênh', 18000, '2024-11-01', N'{"Chức năng": "Điều khiển tải AC/DC", "Điện áp": "5V", "Số kênh": "1"}', 'LSP0015');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module RTC DS3231 (I2C)', 27000, '2025-05-29', N'{"Chức năng": "Đồng hồ thời gian thực", "Điện áp": "3.3-5V", "Số kênh": "N/A"}', 'LSP0015');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Mạch cầu H L298N (2 kênh)', 44000, '2023-09-10', N'{"Chức năng": "Điều khiển động cơ DC", "Điện áp": "12V", "Số kênh": "2"}', 'LSP0015');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Màn hình OLED 0.96 inch I2C (Đơn sắc)', 21600, '2023-06-15', N'{"Loại": "OLED", "Kích thước": "0.96 inch", "Giao tiếp": "I2C", "Màu sắc": "Đơn sắc"}', 'LSP0016');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Màn hình LCD 16x2 (Xanh/Trắng)', 32400, '2024-01-19', N'{"Loại": "LCD", "Kích thước": "16x2 ký tự", "Giao tiếp": "Parallel", "Màu sắc": "Xanh/Trắng"}', 'LSP0016');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Màn hình TFT 2.4 inch SPI (Màu)', 121000, '2024-02-04', N'{"Loại": "TFT", "Kích thước": "2.4 inch", "Giao tiếp": "SPI", "Màu sắc": "Màu"}', 'LSP0016');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'IR LED 5mm', 4500, '2023-07-15', N'{"Chức năng": "Phát hồng ngoại", "Bước sóng": "Infrared", "Kiểu đóng gói": "5mm"}', 'LSP0017');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Photodiode TO-18', 7200, '2024-08-26', N'{"Chức năng": "Phát hiện ánh sáng", "Bước sóng": "Visible", "Kiểu đóng gói": "TO-18"}', 'LSP0017');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Phototransistor DIP-4', 10000, '2024-03-17', N'{"Chức năng": "Chuyển mạch quang", "Bước sóng": "Infrared", "Kiểu đóng gói": "DIP-4"}', 'LSP0017');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Optocoupler PC817 DIP-4', 12000, '2025-04-29', N'{"Chức năng": "Cách ly tín hiệu", "Bước sóng": "Infrared", "Kiểu đóng gói": "DIP-4"}', 'LSP0017');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Laser Diode Module 650nm', 27500, '2024-01-26', N'{"Chức năng": "Phát laser", "Bước sóng": "650nm", "Kiểu đóng gói": "Module"}', 'LSP0017');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây đơn lõi AWG 22 (1m, Đỏ)', 2200, '2023-12-08', N'{"Tiết diện": "AWG 22", "Chất liệu lõi": "Đồng", "Số lõi": "1", "Chiều dài (m)": "1", "Vỏ bọc": "PVC", "Màu sắc": "Đỏ"}', 'LSP0018');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây jumper đực-cái (20cm, Nhiều màu)', 3800, '2025-06-08', N'{"Tiết diện": "N/A", "Chất liệu lõi": "Đồng", "Số lõi": "1", "Chiều dài (m)": "0.2", "Vỏ bọc": "PVC", "Màu sắc": "Nhiều màu"}', 'LSP0018');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây cáp đa lõi 2x0.75mm² (5m, Đen)', 14400, '2025-05-03', N'{"Tiết diện": "0.75 mm²", "Chất liệu lõi": "Đồng", "Số lõi": "2", "Chiều dài (m)": "5", "Vỏ bọc": "PVC", "Màu sắc": "Đen"}', 'LSP0018');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây tín hiệu shielded 4 lõi (10m)', 34000, '2024-03-26', N'{"Tiết diện": "0.5 mm²", "Chất liệu lõi": "Đồng", "Số lõi": "4", "Chiều dài (m)": "10", "Vỏ bọc": "PVC", "Màu sắc": "N/A"}', 'LSP0018');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Dây điện bọc PVC 1.5mm² (50m)', 105600, '2025-03-12', N'{"Tiết diện": "1.5 mm²", "Chất liệu lõi": "Đồng", "Số lõi": "1", "Chiều dài (m)": "50", "Vỏ bọc": "PVC", "Màu sắc": "Xanh"}', 'LSP0018');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Kẹp cá sấu nhỏ (Đỏ)', 10000, '2024-05-16', N'{"Loại": "Kết nối", "Đặc điểm": "N/A"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ dây test Dupont 65 dây', 13500, '2023-10-08', N'{"Loại": "Thử nghiệm mạch", "Đặc điểm": "65 dây"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Mạch testbreadboard 400 lỗ', 18000, '2024-08-07', N'{"Loại": "Thử nghiệm mạch", "Đặc điểm": "400 lỗ"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Que đo đồng hồ vạn năng chất lượng cao', 50000, '2024-04-19', N'{"Loại": "Phụ kiện", "Đặc điểm": "Chất lượng cao"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Thẻ nhớ MicroSD 8GB Class 10', 64000, '2024-01-02', N'{"Loại": "Lưu trữ", "Đặc điểm": "Class 10", "Dung lượng": "8GB"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Thẻ nhớ MicroSD 32GB Class 10', 180000, '2025-06-07', N'{"Loại": "Lưu trữ", "Đặc điểm": "Class 10", "Dung lượng": "32GB"}', 'LSP0019');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Hộp đựng mạch điện tử ABS nhỏ 88x38x26mm', 16000, '2025-02-25', N'{"Chất liệu": "ABS", "Kích thước (mm)": "88x38x26", "Đặc điểm": "Dễ gia công"}', 'LSP0020');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Hộp nhựa chống nước IP65 100x68x50mm', 50000, '2023-06-22', N'{"Chất liệu": "Nhựa ABS", "Kích thước (mm)": "100x68x50", "Đặc điểm": "Chống bụi, nước"}', 'LSP0020');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Hộp nguồn ABS 150x100x70mm', 96000, '2023-12-15', N'{"Chất liệu": "ABS", "Kích thước (mm)": "150x100x70", "Đặc điểm": "Đa năng"}', 'LSP0020');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Vỏ nhôm CNC 150x100x70mm tản nhiệt', 180000, '2024-03-10', N'{"Chất liệu": "Hợp kim nhôm", "Kích thước (mm)": "150x100x70", "Đặc điểm": "Tản nhiệt"}', 'LSP0020');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến cửa từ không dây RF 433MHz', 45000, '2023-12-23', N'{"Giao thức": "RF 433MHz", "Chức năng": "Giám sát an ninh", "Điện áp": "N/A"}', 'LSP0021');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module ESP8266 ESP-01 (Wi-Fi)', 59400, '2024-05-12', N'{"Giao thức": "Wi-Fi", "Chức năng": "Kết nối IoT", "Điện áp": "3.3V"}', 'LSP0021');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module Zigbee CC2530 (Zigbee)', 75600, '2024-01-15', N'{"Giao thức": "Zigbee", "Chức năng": "Kết nối IoT", "Điện áp": "3.3V"}', 'LSP0021');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ điều khiển hồng ngoại Broadlink Mini3 (IR)', 114000, '2024-06-18', N'{"Giao thức": "IR", "Chức năng": "Điều khiển thiết bị gia dụng", "Điện áp": "5V"}', 'LSP0021');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Jack Audio 3.5mm Stereo', 13500, '2025-04-24', N'{"Chức năng": "Kết nối âm thanh", "Công suất": "N/A", "Giao tiếp": "Analog"}', 'LSP0022');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Microphone module MAX9814 (Analog)', 27000, '2024-09-07', N'{"Chức năng": "Thu âm", "Công suất": "N/A", "Giao tiếp": "Analog"}', 'LSP0022');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module khuếch đại âm thanh PAM8403 3W+3W', 24800, '2025-04-13', N'{"Chức năng": "Khuếch đại", "Công suất": "3W+3W", "Giao tiếp": "Analog"}', 'LSP0022');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module thu/phát Bluetooth Audio', 77000, '2023-10-15', N'{"Chức năng": "Truyền/nhận âm thanh không dây", "Công suất": "N/A", "Giao tiếp": "Bluetooth"}', 'LSP0022');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bánh xe Robot 65mm', 27000, '2023-06-14', N'{"Loại": "Bánh xe", "Kích thước": "65mm", "Ứng dụng": "Xe mô hình"}', 'LSP0023');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Động cơ giảm tốc N20 12V', 40000, '2024-08-11', N'{"Loại": "Động cơ", "Kích thước": "12V", "Ứng dụng": "Robot dò đường"}', 'LSP0023');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến dò line 5 kênh', 66000, '2024-01-12', N'{"Loại": "Cảm biến", "Kích thước": "5 kênh", "Ứng dụng": "Robot dò đường"}', 'LSP0023');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module điều khiển động cơ L298N', 70000, '2024-02-09', N'{"Loại": "Điều khiển", "Kích thước": "N/A", "Ứng dụng": "Robot cân bằng"}', 'LSP0023');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Khung Robot dò đường 2WD chassis', 120000, '2024-05-29', N'{"Loại": "Khung", "Kích thước": "2WD chassis", "Ứng dụng": "Robot dò đường"}', 'LSP0023');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module hẹn giờ điện tử 220V AC', 100000, '2024-03-09', N'{"Chức năng": "Hẹn giờ", "Điện áp": "220V AC", "Kết nối": "N/A"}', 'LSP0024');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Công tắc cảm ứng đèn 220V AC', 150000, '2025-02-07', N'{"Chức năng": "Điều khiển chiếu sáng", "Điện áp": "220V AC", "Kết nối": "N/A"}', 'LSP0024');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ điều khiển quạt trần 220V AC (RF)', 180000, '2025-06-07', N'{"Chức năng": "Điều chỉnh tốc độ quạt", "Điện áp": "220V AC", "Kết nối": "RF"}', 'LSP0024');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Ổ cắm thông minh 220V AC (Wi-Fi)', 330000, '2023-07-20', N'{"Chức năng": "Điều khiển thiết bị từ xa", "Điện áp": "220V AC", "Kết nối": "Wi-Fi"}', 'LSP0024');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Cảm biến tiệm cận Inductive NPN 24V DC', 190000, '2024-04-16', N'{"Loại": "Proximity Sensor", "Điện áp": "24V DC", "Đầu ra": "NPN", "Ứng dụng": "Tự động hóa"}', 'LSP0025');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Relay SSR công nghiệp 220V AC', 297000, '2024-08-21', N'{"Loại": "Solid State Relay", "Điện áp": "220V AC", "Đầu ra": "Digital", "Ứng dụng": "Điều khiển máy móc"}', 'LSP0025');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ chuyển đổi tín hiệu 4-20mA 24V DC', 440000, '2024-02-04', N'{"Loại": "Signal Converter", "Điện áp": "24V DC", "Đầu ra": "4-20mA", "Ứng dụng": "Giám sát quy trình"}', 'LSP0025');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'PLC (Programmable Logic Controller) cơ bản', 900000, '2024-08-16', N'{"Loại": "Controller", "Điện áp": "24V DC", "Đầu ra": "Digital", "Ứng dụng": "Tự động hóa"}', 'LSP0025');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Module camera OV2640 2MP', 720000, '2024-05-15', N'{"Loại": "Camera Module", "Tính năng": "2MP", "Ứng dụng": "Embedded Vision"}', 'LSP0026');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Board phát triển ESP32 DevKitC (Wi-Fi, Bluetooth)', 1000000, '2023-09-19', N'{"Loại": "Development Board", "Tính năng": "Wi-Fi, Bluetooth", "Ứng dụng": "IoT projects"}', 'LSP0026');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Kit Raspberry Pi 4 Model B 4GB RAM', 3000000, '2024-02-29', N'{"Loại": "Single Board Computer", "Tính năng": "4GB RAM", "Ứng dụng": "Robotics"}', 'LSP0026');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ điều khiển Drone Pixhawk (GPS, IMU)', 3850000, '2025-02-06', N'{"Loại": "Flight Controller", "Tính năng": "GPS, IMU", "Ứng dụng": "Drones"}', 'LSP0026');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ dụng cụ sửa chữa điện tử đa năng', 360000, '2023-08-10', N'{"Nội dung": "Mỏ hàn, đồng hồ, kìm", "Đối tượng": "Thợ sửa chữa"}', 'LSP0001');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Kit học lập trình MicroPython với ESP32', 600000, '2025-06-07', N'{"Nội dung": "ESP32, cảm biến, dây dẫn", "Đối tượng": "Học sinh, sinh viên"}', 'LSP0001');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Bộ kit Arduino Uno cơ bản', 840000, '2025-02-02', N'{"Nội dung": "Arduino Uno, cảm biến, linh kiện", "Đối tượng": "Người mới bắt đầu"}', 'LSP0001');
INSERT INTO SanPham (TenSanPham, DonGia, NgaySanXuat, ThongSoKyThuat, MaLoaiSanPham) VALUES (N'Combo Smart Home khởi động', 1650000, '2024-08-10', N'{"Nội dung": "Hub, cảm biến cửa, ổ cắm thông minh", "Đối tượng": "Người yêu thích IoT"}', 'LSP0001');

-- SQL INSERT Statements for ViTriDungSanPham
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 01');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 02');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 03');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 04');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-4-Ngăn 05');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 06');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 07');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 08');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 09');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-2-Ngăn 10');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 11');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 12');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 13');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-2-Ngăn 14');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 15');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 16');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 17');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-1-Ngăn 18');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 19');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-2-Ngăn 20');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-2-Ngăn 21');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-4-Ngăn 22');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 23');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-5-Ngăn 24');
INSERT INTO ViTriDungSanPham (TenNganDung) VALUES (N'Kệ A-3-Ngăn 25');

-- SQL INSERT Statements for ChiTietViTri (Each bin holds only one type of product)
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0014', 'SP0086', 159);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0016', 'SP0051', 188);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0017', 'SP0124', 98);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0024', 'SP0026', 165);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0010', 'SP0048', 68);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0015', 'SP0013', 87);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0003', 'SP0032', 187);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0007', 'SP0042', 72);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0002', 'SP0078', 91);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0012', 'SP0060', 53);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0023', 'SP0008', 18);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0013', 'SP0106', 199);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0009', 'SP0002', 118);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0001', 'SP0095', 88);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0025', 'SP0105', 7);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0004', 'SP0034', 39);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0020', 'SP0070', 15);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0021', 'SP0095', 148);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0022', 'SP0104', 61);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0008', 'SP0031', 83);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0018', 'SP0019', 77);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0019', 'SP0022', 171);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0005', 'SP0106', 147);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0011', 'SP0032', 45);
INSERT INTO ChiTietViTri (MaNganDung, MaSanPham, SoLuong) VALUES ('N0006', 'SP0047', 182);


-- SQL INSERT Statements for HoaDon
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH020', NULL, NULL, 'NV001', '2024-07-21', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV004', '2025-05-23', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH006', NULL, NULL, 'NV003', '2024-11-24', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH009', NULL, NULL, 'NV005', '2023-07-07', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH007', NULL, NULL, 'NV004', '2024-03-09', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phạm Văn Mai', '0220066964', 'NV002', '2023-08-04', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH003', NULL, NULL, 'NV005', '2024-12-26', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH014', NULL, NULL, 'NV005', '2023-07-02', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV003', '2023-09-29', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH014', NULL, NULL, 'NV001', '2024-02-06', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH007', NULL, NULL, 'NV001', '2025-04-12', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV002', '2025-04-25', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV001', '2024-03-09', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV002', '2025-02-25', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phan Quang Long', '0615788157', 'NV001', '2025-01-06', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH014', NULL, NULL, 'NV002', '2025-03-15', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV001', '2024-01-13', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV003', '2023-10-09', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH008', NULL, NULL, 'NV003', '2024-02-22', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV002', '2023-08-13', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Nguyễn Hồng Tùng', '0194349482', 'NV005', '2025-03-06', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV001', '2023-10-05', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV004', '2024-10-26', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phan Kim Thảo', '0025143108', 'NV004', '2023-09-30', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phạm Minh Nam', '0775033888', 'NV005', '2025-04-05', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH013', NULL, NULL, 'NV002', '2025-01-08', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH005', NULL, NULL, 'NV001', '2023-09-05', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH011', NULL, NULL, 'NV004', '2023-08-02', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH003', NULL, NULL, 'NV004', '2024-07-06', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Vũ Gia Tùng', '0754434473', 'NV002', '2024-07-08', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH001', NULL, NULL, 'NV001', '2025-02-06', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV004', '2023-11-14', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Trần Thị Nam', '0852740592', 'NV004', '2024-05-11', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phạm Thanh Phúc', '0218095967', 'NV005', '2024-06-23', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phan Văn Uyên', '0147428327', 'NV003', '2024-05-11', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH014', NULL, NULL, 'NV004', '2025-04-27', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV002', '2024-02-19', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV004', '2024-06-30', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV002', '2023-10-03', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH001', NULL, NULL, 'NV002', '2024-04-17', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH020', NULL, NULL, 'NV001', '2024-09-19', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Trần Châu', '0070044539', 'NV002', '2024-05-19', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Nguyễn Tùng', '0577557176', 'NV003', '2024-09-11', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Trần Nam', '0031909659', 'NV002', '2024-02-17', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV004', '2024-07-18', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Trần Minh Dung', '0119369631', 'NV001', '2023-09-06', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH004', NULL, NULL, 'NV005', '2023-06-30', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH004', NULL, NULL, 'NV003', '2023-09-03', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH019', NULL, NULL, 'NV001', '2023-06-23', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phan Gia Long', '0618301200', 'NV003', '2024-05-03', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV004', '2025-06-01', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Vũ Văn Uyên', '0643215887', 'NV003', '2023-10-04', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH007', NULL, NULL, 'NV003', '2024-08-25', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV003', '2023-06-28', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Lê Phúc', '0858572569', 'NV002', '2023-12-03', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV005', '2023-10-14', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH007', NULL, NULL, 'NV005', '2023-09-01', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV003', '2024-06-08', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH019', NULL, NULL, 'NV003', '2023-11-16', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH020', NULL, NULL, 'NV003', '2023-06-23', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Bùi Thị Tùng', '0849974798', 'NV003', '2023-12-18', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Nguyễn Quang Hải', '0888987699', 'NV003', '2024-02-24', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH017', NULL, NULL, 'NV002', '2023-10-07', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH006', NULL, NULL, 'NV001', '2024-02-23', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH017', NULL, NULL, 'NV003', '2024-02-01', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV001', '2023-12-03', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV003', '2023-12-31', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH003', NULL, NULL, 'NV001', '2023-09-10', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH018', NULL, NULL, 'NV005', '2023-10-16', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phạm Hồng Hải', '0927260066', 'NV001', '2024-01-13', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH020', NULL, NULL, 'NV002', '2025-01-22', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH019', NULL, NULL, 'NV005', '2023-11-23', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH005', NULL, NULL, 'NV004', '2024-06-14', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Huỳnh Quang Dung', '0793509705', 'NV004', '2024-09-16', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV004', '2024-08-23', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV001', '2023-12-19', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV005', '2025-05-08', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH013', NULL, NULL, 'NV003', '2025-03-24', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH007', NULL, NULL, 'NV004', '2023-08-11', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH008', NULL, NULL, 'NV004', '2023-10-04', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH010', NULL, NULL, 'NV003', '2024-05-07', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV002', '2023-10-21', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH017', NULL, NULL, 'NV001', '2024-09-12', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Bùi Mai', '0410842237', 'NV004', '2025-04-16', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH002', NULL, NULL, 'NV001', '2023-09-14', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH006', NULL, NULL, 'NV002', '2024-03-16', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV002', '2025-04-05', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV001', '2023-09-11', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH013', NULL, NULL, 'NV003', '2023-07-23', N'Khác');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH016', NULL, NULL, 'NV001', '2024-12-10', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES (NULL, N'Phan Nam', '0703813009', 'NV002', '2025-04-07', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH004', NULL, NULL, 'NV005', '2023-07-06', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH001', NULL, NULL, 'NV003', '2024-08-27', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH019', NULL, NULL, 'NV002', '2024-03-25', N'Chuyển khoản');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH003', NULL, NULL, 'NV004', '2023-12-15', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH015', NULL, NULL, 'NV003', '2023-10-17', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH012', NULL, NULL, 'NV003', '2023-11-20', N'Tiền mặt');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH001', NULL, NULL, 'NV001', '2023-07-31', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH008', NULL, NULL, 'NV001', '2025-06-01', N'Thẻ tín dụng');
INSERT INTO HoaDon (MaKhachHang, TenKhachHangVangLai, SDTKhachHangVangLai, MaNhanVienLap, NgayBan, PhuongThucThanhToan) VALUES ('KH018', NULL, NULL, 'NV001', '2024-06-03', N'Khác');

-- SQL INSERT Statements for ChiTietHoaDon
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (1, 'SP0050', 2, 39600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (1, 'SP0110', 2, 300000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (1, 'SP0066', 6, 150000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (2, 'SP0108', 2, 240000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (2, 'SP0081', 10, 22000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (3, 'SP0033', 5, 605000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (3, 'SP0015', 8, 50400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (3, 'SP0054', 7, 3500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (4, 'SP0093', 10, 500000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (4, 'SP0087', 9, 121500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (4, 'SP0095', 3, 540000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (4, 'SP0021', 8, 518400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (5, 'SP0078', 6, 60000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (5, 'SP0121', 10, 3600000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (6, 'SP0051', 6, 116400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (6, 'SP0088', 2, 36000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (7, 'SP0060', 9, 594000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (7, 'SP0055', 4, 21600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (7, 'SP0105', 4, 160000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (7, 'SP0104', 2, 54000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (7, 'SP0110', 7, 1050000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (8, 'SP0087', 8, 108000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (8, 'SP0115', 10, 4400000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (8, 'SP0083', 10, 144000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (9, 'SP0036', 4, 11200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (9, 'SP0119', 8, 24000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (10, 'SP0035', 9, 9900);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (10, 'SP0054', 3, 1500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (11, 'SP0086', 8, 80000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (11, 'SP0115', 10, 4400000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (11, 'SP0084', 9, 306000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (11, 'SP0116', 9, 8100000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (12, 'SP0012', 5, 36500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (12, 'SP0077', 3, 21600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (12, 'SP0069', 2, 32400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (12, 'SP0018', 6, 297000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (13, 'SP0121', 5, 1800000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (13, 'SP0030', 10, 120000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (13, 'SP0066', 4, 100000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (14, 'SP0082', 6, 22800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (14, 'SP0078', 1, 10000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (14, 'SP0028', 8, 640000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (14, 'SP0040', 8, 288800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (15, 'SP0091', 1, 180000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (15, 'SP0028', 2, 160000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (16, 'SP0061', 9, 1188000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (16, 'SP0080', 2, 55000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (17, 'SP0095', 10, 1800000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (17, 'SP0062', 9, 1458000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (17, 'SP0026', 1, 27000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (17, 'SP0025', 9, 135000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (17, 'SP0032', 7, 280000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (18, 'SP0097', 3, 178200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (18, 'SP0014', 3, 21600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (19, 'SP0095', 2, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (20, 'SP0072', 7, 308000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (20, 'SP0065', 7, 126000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (20, 'SP0084', 7, 238000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (20, 'SP0023', 2, 665600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (20, 'SP0102', 8, 198400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (21, 'SP0052', 9, 544500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (22, 'SP0015', 9, 56700);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (22, 'SP0085', 9, 950400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (22, 'SP0038', 10, 92000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (23, 'SP0045', 7, 204400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (23, 'SP0113', 1, 190000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (23, 'SP0016', 5, 44500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (24, 'SP0034', 7, 5600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (24, 'SP0106', 9, 594000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (24, 'SP0095', 2, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (25, 'SP0085', 8, 844800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (25, 'SP0054', 3, 1500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (25, 'SP0042', 10, 758000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (25, 'SP0001', 9, 2700);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (26, 'SP0016', 1, 8900);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (27, 'SP0054', 10, 5000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (27, 'SP0038', 7, 64400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (27, 'SP0094', 7, 672000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (27, 'SP0115', 5, 2200000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (28, 'SP0011', 1, 3500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (28, 'SP0069', 3, 48600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (28, 'SP0003', 4, 2000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (29, 'SP0067', 10, 605000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (30, 'SP0029', 4, 880000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (30, 'SP0008', 9, 10800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (30, 'SP0097', 8, 475200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (30, 'SP0023', 8, 2662400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (30, 'SP0043', 3, 495000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (31, 'SP0070', 6, 108000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (31, 'SP0093', 1, 50000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (31, 'SP0018', 8, 396000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (31, 'SP0012', 2, 14600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (31, 'SP0024', 1, 10000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (32, 'SP0118', 9, 9000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (33, 'SP0019', 8, 230400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (33, 'SP0093', 9, 450000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (34, 'SP0020', 9, 709200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (34, 'SP0077', 5, 36000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (34, 'SP0084', 5, 170000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (34, 'SP0049', 5, 48000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (35, 'SP0023', 6, 1996800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (35, 'SP0082', 10, 38000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (35, 'SP0114', 2, 594000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (36, 'SP0079', 9, 108000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (37, 'SP0105', 8, 320000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (37, 'SP0067', 3, 181500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (37, 'SP0077', 8, 57600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (37, 'SP0034', 1, 800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (38, 'SP0008', 4, 4800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (38, 'SP0118', 4, 4000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (39, 'SP0022', 1, 86400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (40, 'SP0107', 5, 350000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (40, 'SP0095', 2, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (40, 'SP0053', 7, 175000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (41, 'SP0066', 8, 200000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (42, 'SP0057', 10, 545000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (42, 'SP0091', 5, 900000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (42, 'SP0062', 9, 1458000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (42, 'SP0043', 1, 165000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (42, 'SP0059', 6, 211200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (43, 'SP0074', 8, 259200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (44, 'SP0078', 2, 20000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (45, 'SP0079', 6, 72000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (45, 'SP0101', 7, 189000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (45, 'SP0004', 8, 5600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (45, 'SP0092', 3, 48000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (45, 'SP0106', 7, 462000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (46, 'SP0075', 1, 121000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (46, 'SP0003', 1, 500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (46, 'SP0099', 2, 228000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (47, 'SP0052', 10, 605000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (47, 'SP0054', 6, 3000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (48, 'SP0115', 8, 3520000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (48, 'SP0078', 3, 30000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (48, 'SP0018', 8, 396000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (49, 'SP0074', 1, 32400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (49, 'SP0023', 9, 2995200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (50, 'SP0045', 10, 292000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (51, 'SP0031', 1, 24300);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (51, 'SP0120', 6, 23100000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (51, 'SP0061', 4, 528000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (52, 'SP0108', 7, 840000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (52, 'SP0085', 4, 422400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (53, 'SP0121', 10, 3600000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (53, 'SP0051', 5, 97000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (53, 'SP0055', 1, 5400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (54, 'SP0003', 2, 1000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (54, 'SP0079', 10, 120000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (54, 'SP0093', 10, 500000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (54, 'SP0002', 3, 2100);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (54, 'SP0078', 8, 80000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (55, 'SP0002', 7, 4900);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (55, 'SP0099', 8, 912000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (55, 'SP0023', 9, 2995200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (55, 'SP0071', 3, 81000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (56, 'SP0083', 1, 14400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (57, 'SP0087', 4, 54000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (57, 'SP0018', 1, 49500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (57, 'SP0009', 7, 21000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (58, 'SP0067', 3, 181500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (58, 'SP0092', 7, 112000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (58, 'SP0016', 4, 35600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (59, 'SP0103', 10, 770000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (59, 'SP0028', 8, 640000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (59, 'SP0027', 9, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (59, 'SP0085', 5, 528000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (60, 'SP0052', 2, 121000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (60, 'SP0010', 6, 9600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (60, 'SP0004', 6, 4200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (60, 'SP0041', 7, 317800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (61, 'SP0004', 4, 2800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (61, 'SP0062', 8, 1296000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (61, 'SP0057', 10, 545000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (61, 'SP0082', 1, 3800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (62, 'SP0038', 5, 46000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (63, 'SP0057', 7, 381500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (63, 'SP0004', 5, 3500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (63, 'SP0094', 7, 672000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (63, 'SP0063', 7, 45500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (64, 'SP0090', 2, 128000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (64, 'SP0053', 10, 250000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (65, 'SP0124', 5, 8250000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (66, 'SP0027', 4, 160000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (66, 'SP0086', 9, 90000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (66, 'SP0002', 9, 6300);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (67, 'SP0034', 6, 4800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (67, 'SP0065', 9, 162000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (67, 'SP0028', 9, 720000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (67, 'SP0037', 2, 12600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (67, 'SP0080', 3, 82500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (68, 'SP0072', 2, 88000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (68, 'SP0061', 9, 1188000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (68, 'SP0075', 9, 1089000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (69, 'SP0113', 6, 1140000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (69, 'SP0034', 8, 6400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (69, 'SP0029', 3, 660000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (69, 'SP0002', 7, 4900);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (70, 'SP0094', 1, 96000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (70, 'SP0028', 4, 320000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (70, 'SP0097', 3, 178200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (70, 'SP0088', 8, 144000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (71, 'SP0111', 6, 1080000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (71, 'SP0071', 8, 216000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (71, 'SP0022', 6, 518400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (71, 'SP0008', 4, 4800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (72, 'SP0025', 7, 105000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (72, 'SP0026', 7, 189000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (72, 'SP0087', 6, 81000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (72, 'SP0073', 4, 86400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (73, 'SP0063', 7, 45500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (73, 'SP0087', 10, 135000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (73, 'SP0039', 7, 14700);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (73, 'SP0022', 2, 172800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (74, 'SP0007', 3, 3000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (74, 'SP0104', 7, 189000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (74, 'SP0083', 6, 86400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (75, 'SP0118', 1, 1000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (75, 'SP0103', 10, 770000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (75, 'SP0011', 4, 14000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (76, 'SP0035', 4, 4400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (76, 'SP0097', 1, 59400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (76, 'SP0049', 4, 38400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (76, 'SP0107', 8, 560000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (77, 'SP0099', 8, 912000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (77, 'SP0052', 8, 484000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (77, 'SP0034', 7, 5600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (77, 'SP0105', 8, 320000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (78, 'SP0107', 10, 700000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (78, 'SP0057', 6, 327000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (78, 'SP0065', 7, 126000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (79, 'SP0100', 3, 40500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (79, 'SP0013', 10, 216000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (80, 'SP0001', 2, 600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (80, 'SP0113', 2, 380000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (80, 'SP0119', 2, 6000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (80, 'SP0106', 1, 66000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (80, 'SP0007', 3, 3000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (81, 'SP0064', 10, 108000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (81, 'SP0121', 3, 1080000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (81, 'SP0001', 7, 2100);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (82, 'SP0071', 5, 135000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (82, 'SP0062', 5, 810000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (82, 'SP0096', 8, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (83, 'SP0084', 3, 102000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (84, 'SP0115', 9, 3960000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (84, 'SP0013', 1, 21600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (85, 'SP0117', 1, 720000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (85, 'SP0068', 8, 108000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (85, 'SP0074', 8, 259200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (86, 'SP0030', 8, 96000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (86, 'SP0027', 9, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (86, 'SP0077', 3, 21600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (86, 'SP0020', 2, 157600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (86, 'SP0057', 10, 545000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (87, 'SP0030', 6, 72000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (87, 'SP0110', 2, 300000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (87, 'SP0022', 8, 691200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (87, 'SP0052', 4, 242000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (88, 'SP0097', 4, 237600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (89, 'SP0024', 8, 80000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (89, 'SP0036', 8, 22400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (89, 'SP0111', 2, 360000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (90, 'SP0108', 10, 1200000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (90, 'SP0059', 8, 281600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (91, 'SP0121', 8, 2880000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (91, 'SP0045', 5, 146000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (92, 'SP0039', 6, 12600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (92, 'SP0083', 9, 129600);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (92, 'SP0019', 8, 230400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (92, 'SP0077', 1, 7200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (92, 'SP0013', 3, 64800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (93, 'SP0046', 4, 272000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (94, 'SP0013', 3, 64800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (94, 'SP0034', 9, 7200);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (94, 'SP0068', 5, 67500);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (95, 'SP0020', 1, 78800);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (95, 'SP0009', 6, 18000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (95, 'SP0116', 10, 9000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (96, 'SP0017', 6, 165000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (96, 'SP0005', 4, 2400);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (96, 'SP0072', 6, 264000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (96, 'SP0040', 1, 36100);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (97, 'SP0111', 8, 1440000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (97, 'SP0099', 7, 798000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (98, 'SP0054', 6, 3000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (99, 'SP0118', 2, 2000000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (99, 'SP0033', 6, 726000);
INSERT INTO ChiTietHoaDon (MaHoaDon, MaSanPham, SoLuong, ThanhTien) VALUES (100, 'SP0105', 7, 280000);

-- SQL INSERT Statements for PhieuNhapHang
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-05-16', 'NV005');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2023-07-11', 'NV005');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2023-11-27', 'NV002');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-04-21', 'NV004');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2025-03-22', 'NV003');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-07-23', 'NV001');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-12-10', 'NV002');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2025-05-09', 'NV002');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-12-03', 'NV003');
INSERT INTO PhieuNhapHang (NgayNhap, MaNhanVienThucHien) VALUES ('2024-11-22', 'NV003');

-- SQL INSERT Statements for ChiTietPhieuNhap
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0055', 44, 4800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0061', 33, 101300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0040', 33, 25300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0083', 6, 10700);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0016', 43, 6600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0121', 12, 277000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0105', 12, 32700);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (1, 'SP0037', 13, 4800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (2, 'SP0066', 22, 18800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (2, 'SP0087', 14, 11000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (2, 'SP0079', 41, 9100);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (2, 'SP0008', 24, 1000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0051', 7, 14800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0087', 36, 11600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0073', 24, 17900);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0064', 12, 8000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0100', 16, 11100);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0030', 20, 10300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (3, 'SP0078', 25, 8500);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (4, 'SP0044', 9, 274600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (4, 'SP0032', 25, 34800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (4, 'SP0103', 32, 67200);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (4, 'SP0108', 38, 93500);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0064', 49, 7900);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0121', 36, 261600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0079', 35, 10200);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0102', 13, 21000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0043', 19, 129000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0050', 18, 14500);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0100', 47, 9700);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (5, 'SP0049', 23, 8300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (6, 'SP0122', 46, 441800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (6, 'SP0118', 18, 770100);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (6, 'SP0030', 19, 9300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (6, 'SP0121', 7, 313100);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (7, 'SP0042', 21, 61600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (7, 'SP0012', 25, 5500);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (7, 'SP0080', 46, 23300);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (8, 'SP0102', 7, 21800);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (8, 'SP0006', 37, 900);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (8, 'SP0008', 17, 1000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (9, 'SP0074', 29, 26000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (9, 'SP0091', 34, 146300 );
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (9, 'SP0111', 7, 133000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (9, 'SP0023', 47, 257500);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (9, 'SP0028', 47, 56000);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (10, 'SP0064', 18, 7900);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (10, 'SP0038', 17, 7600);
INSERT INTO ChiTietPhieuNhap (MaPhieuNhap, MaSanPham, SoLuong, DonGiaNhap) VALUES (10, 'SP0023', 16, 233300);


-- SQL INSERT Statements for SaoLuu
INSERT INTO SaoLuu (NgaySaoLuu, LoaiSaoLuu, MaNguoiDungThucHien, ViTriLuuTru) VALUES ('2025-04-11 00:00:00', N'Differential', 'TK003', N'D:\DatabaseBackups\SmartComponentShop\Differential_20250611000000_01.bak');
INSERT INTO SaoLuu (NgaySaoLuu, LoaiSaoLuu, MaNguoiDungThucHien, ViTriLuuTru) VALUES ('2024-12-17 00:00:00', N'Full', 'TK001', N'D:\DatabaseBackups\SmartComponentShop\Full_20250611000000_02.bak');

-- SQL INSERT Statements for PhucHoi
INSERT INTO PhucHoi (NgayPhucHoi, LoaiPhucHoi, MaNguoiDungThucHien, MaSaoLuu) VALUES ('2025-03-13 00:00:00', N'Differential', 'TK003', 2);
